// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/datamodel.proto

package com.packt.masteringakka.bookstore.credit;

public final class Datamodel {
  private Datamodel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CreditCardInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string cardHolder = 1;
    /**
     * <code>required string cardHolder = 1;</code>
     */
    boolean hasCardHolder();
    /**
     * <code>required string cardHolder = 1;</code>
     */
    java.lang.String getCardHolder();
    /**
     * <code>required string cardHolder = 1;</code>
     */
    com.google.protobuf.ByteString
        getCardHolderBytes();

    // required string cardType = 2;
    /**
     * <code>required string cardType = 2;</code>
     */
    boolean hasCardType();
    /**
     * <code>required string cardType = 2;</code>
     */
    java.lang.String getCardType();
    /**
     * <code>required string cardType = 2;</code>
     */
    com.google.protobuf.ByteString
        getCardTypeBytes();

    // required string cardNumber = 3;
    /**
     * <code>required string cardNumber = 3;</code>
     */
    boolean hasCardNumber();
    /**
     * <code>required string cardNumber = 3;</code>
     */
    java.lang.String getCardNumber();
    /**
     * <code>required string cardNumber = 3;</code>
     */
    com.google.protobuf.ByteString
        getCardNumberBytes();

    // required int64 expiration = 4;
    /**
     * <code>required int64 expiration = 4;</code>
     */
    boolean hasExpiration();
    /**
     * <code>required int64 expiration = 4;</code>
     */
    long getExpiration();
  }
  /**
   * Protobuf type {@code com.packt.masteringakka.bookstore.credit.CreditCardInfo}
   */
  public static final class CreditCardInfo extends
      com.google.protobuf.GeneratedMessage
      implements CreditCardInfoOrBuilder {
    // Use CreditCardInfo.newBuilder() to construct.
    private CreditCardInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CreditCardInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CreditCardInfo defaultInstance;
    public static CreditCardInfo getDefaultInstance() {
      return defaultInstance;
    }

    public CreditCardInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CreditCardInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              cardHolder_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              cardType_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              cardNumber_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              expiration_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.packt.masteringakka.bookstore.credit.Datamodel.internal_static_com_packt_masteringakka_bookstore_credit_CreditCardInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.packt.masteringakka.bookstore.credit.Datamodel.internal_static_com_packt_masteringakka_bookstore_credit_CreditCardInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo.class, com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<CreditCardInfo> PARSER =
        new com.google.protobuf.AbstractParser<CreditCardInfo>() {
      public CreditCardInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreditCardInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CreditCardInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string cardHolder = 1;
    public static final int CARDHOLDER_FIELD_NUMBER = 1;
    private java.lang.Object cardHolder_;
    /**
     * <code>required string cardHolder = 1;</code>
     */
    public boolean hasCardHolder() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string cardHolder = 1;</code>
     */
    public java.lang.String getCardHolder() {
      java.lang.Object ref = cardHolder_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cardHolder_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string cardHolder = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCardHolderBytes() {
      java.lang.Object ref = cardHolder_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardHolder_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string cardType = 2;
    public static final int CARDTYPE_FIELD_NUMBER = 2;
    private java.lang.Object cardType_;
    /**
     * <code>required string cardType = 2;</code>
     */
    public boolean hasCardType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string cardType = 2;</code>
     */
    public java.lang.String getCardType() {
      java.lang.Object ref = cardType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cardType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string cardType = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCardTypeBytes() {
      java.lang.Object ref = cardType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string cardNumber = 3;
    public static final int CARDNUMBER_FIELD_NUMBER = 3;
    private java.lang.Object cardNumber_;
    /**
     * <code>required string cardNumber = 3;</code>
     */
    public boolean hasCardNumber() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string cardNumber = 3;</code>
     */
    public java.lang.String getCardNumber() {
      java.lang.Object ref = cardNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cardNumber_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string cardNumber = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCardNumberBytes() {
      java.lang.Object ref = cardNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 expiration = 4;
    public static final int EXPIRATION_FIELD_NUMBER = 4;
    private long expiration_;
    /**
     * <code>required int64 expiration = 4;</code>
     */
    public boolean hasExpiration() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 expiration = 4;</code>
     */
    public long getExpiration() {
      return expiration_;
    }

    private void initFields() {
      cardHolder_ = "";
      cardType_ = "";
      cardNumber_ = "";
      expiration_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCardHolder()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCardType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCardNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasExpiration()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCardHolderBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCardTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getCardNumberBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, expiration_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCardHolderBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCardTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getCardNumberBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, expiration_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.packt.masteringakka.bookstore.credit.CreditCardInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.packt.masteringakka.bookstore.credit.Datamodel.internal_static_com_packt_masteringakka_bookstore_credit_CreditCardInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.packt.masteringakka.bookstore.credit.Datamodel.internal_static_com_packt_masteringakka_bookstore_credit_CreditCardInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo.class, com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo.Builder.class);
      }

      // Construct using com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cardHolder_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        cardType_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        cardNumber_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        expiration_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.packt.masteringakka.bookstore.credit.Datamodel.internal_static_com_packt_masteringakka_bookstore_credit_CreditCardInfo_descriptor;
      }

      public com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo getDefaultInstanceForType() {
        return com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo.getDefaultInstance();
      }

      public com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo build() {
        com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo buildPartial() {
        com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo result = new com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cardHolder_ = cardHolder_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cardType_ = cardType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.cardNumber_ = cardNumber_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.expiration_ = expiration_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo) {
          return mergeFrom((com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo other) {
        if (other == com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo.getDefaultInstance()) return this;
        if (other.hasCardHolder()) {
          bitField0_ |= 0x00000001;
          cardHolder_ = other.cardHolder_;
          onChanged();
        }
        if (other.hasCardType()) {
          bitField0_ |= 0x00000002;
          cardType_ = other.cardType_;
          onChanged();
        }
        if (other.hasCardNumber()) {
          bitField0_ |= 0x00000004;
          cardNumber_ = other.cardNumber_;
          onChanged();
        }
        if (other.hasExpiration()) {
          setExpiration(other.getExpiration());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCardHolder()) {
          
          return false;
        }
        if (!hasCardType()) {
          
          return false;
        }
        if (!hasCardNumber()) {
          
          return false;
        }
        if (!hasExpiration()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string cardHolder = 1;
      private java.lang.Object cardHolder_ = "";
      /**
       * <code>required string cardHolder = 1;</code>
       */
      public boolean hasCardHolder() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string cardHolder = 1;</code>
       */
      public java.lang.String getCardHolder() {
        java.lang.Object ref = cardHolder_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          cardHolder_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string cardHolder = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCardHolderBytes() {
        java.lang.Object ref = cardHolder_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cardHolder_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string cardHolder = 1;</code>
       */
      public Builder setCardHolder(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        cardHolder_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string cardHolder = 1;</code>
       */
      public Builder clearCardHolder() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cardHolder_ = getDefaultInstance().getCardHolder();
        onChanged();
        return this;
      }
      /**
       * <code>required string cardHolder = 1;</code>
       */
      public Builder setCardHolderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        cardHolder_ = value;
        onChanged();
        return this;
      }

      // required string cardType = 2;
      private java.lang.Object cardType_ = "";
      /**
       * <code>required string cardType = 2;</code>
       */
      public boolean hasCardType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string cardType = 2;</code>
       */
      public java.lang.String getCardType() {
        java.lang.Object ref = cardType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          cardType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string cardType = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCardTypeBytes() {
        java.lang.Object ref = cardType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cardType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string cardType = 2;</code>
       */
      public Builder setCardType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        cardType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string cardType = 2;</code>
       */
      public Builder clearCardType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cardType_ = getDefaultInstance().getCardType();
        onChanged();
        return this;
      }
      /**
       * <code>required string cardType = 2;</code>
       */
      public Builder setCardTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        cardType_ = value;
        onChanged();
        return this;
      }

      // required string cardNumber = 3;
      private java.lang.Object cardNumber_ = "";
      /**
       * <code>required string cardNumber = 3;</code>
       */
      public boolean hasCardNumber() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string cardNumber = 3;</code>
       */
      public java.lang.String getCardNumber() {
        java.lang.Object ref = cardNumber_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          cardNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string cardNumber = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCardNumberBytes() {
        java.lang.Object ref = cardNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cardNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string cardNumber = 3;</code>
       */
      public Builder setCardNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        cardNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string cardNumber = 3;</code>
       */
      public Builder clearCardNumber() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cardNumber_ = getDefaultInstance().getCardNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required string cardNumber = 3;</code>
       */
      public Builder setCardNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        cardNumber_ = value;
        onChanged();
        return this;
      }

      // required int64 expiration = 4;
      private long expiration_ ;
      /**
       * <code>required int64 expiration = 4;</code>
       */
      public boolean hasExpiration() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 expiration = 4;</code>
       */
      public long getExpiration() {
        return expiration_;
      }
      /**
       * <code>required int64 expiration = 4;</code>
       */
      public Builder setExpiration(long value) {
        bitField0_ |= 0x00000008;
        expiration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 expiration = 4;</code>
       */
      public Builder clearExpiration() {
        bitField0_ = (bitField0_ & ~0x00000008);
        expiration_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.packt.masteringakka.bookstore.credit.CreditCardInfo)
    }

    static {
      defaultInstance = new CreditCardInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.packt.masteringakka.bookstore.credit.CreditCardInfo)
  }

  public interface CreditCardTransactionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string id = 1;
    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // required .com.packt.masteringakka.bookstore.credit.CreditCardInfo cardInfo = 2;
    /**
     * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardInfo cardInfo = 2;</code>
     */
    boolean hasCardInfo();
    /**
     * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardInfo cardInfo = 2;</code>
     */
    com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo getCardInfo();
    /**
     * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardInfo cardInfo = 2;</code>
     */
    com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfoOrBuilder getCardInfoOrBuilder();

    // required double amount = 3;
    /**
     * <code>required double amount = 3;</code>
     */
    boolean hasAmount();
    /**
     * <code>required double amount = 3;</code>
     */
    double getAmount();

    // required string status = 4;
    /**
     * <code>required string status = 4;</code>
     */
    boolean hasStatus();
    /**
     * <code>required string status = 4;</code>
     */
    java.lang.String getStatus();
    /**
     * <code>required string status = 4;</code>
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    // optional string confirmationCode = 5;
    /**
     * <code>optional string confirmationCode = 5;</code>
     */
    boolean hasConfirmationCode();
    /**
     * <code>optional string confirmationCode = 5;</code>
     */
    java.lang.String getConfirmationCode();
    /**
     * <code>optional string confirmationCode = 5;</code>
     */
    com.google.protobuf.ByteString
        getConfirmationCodeBytes();

    // required int64 createTs = 6;
    /**
     * <code>required int64 createTs = 6;</code>
     */
    boolean hasCreateTs();
    /**
     * <code>required int64 createTs = 6;</code>
     */
    long getCreateTs();
  }
  /**
   * Protobuf type {@code com.packt.masteringakka.bookstore.credit.CreditCardTransaction}
   */
  public static final class CreditCardTransaction extends
      com.google.protobuf.GeneratedMessage
      implements CreditCardTransactionOrBuilder {
    // Use CreditCardTransaction.newBuilder() to construct.
    private CreditCardTransaction(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CreditCardTransaction(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CreditCardTransaction defaultInstance;
    public static CreditCardTransaction getDefaultInstance() {
      return defaultInstance;
    }

    public CreditCardTransaction getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CreditCardTransaction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = cardInfo_.toBuilder();
              }
              cardInfo_ = input.readMessage(com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(cardInfo_);
                cardInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              amount_ = input.readDouble();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              status_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              confirmationCode_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              createTs_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.packt.masteringakka.bookstore.credit.Datamodel.internal_static_com_packt_masteringakka_bookstore_credit_CreditCardTransaction_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.packt.masteringakka.bookstore.credit.Datamodel.internal_static_com_packt_masteringakka_bookstore_credit_CreditCardTransaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction.class, com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction.Builder.class);
    }

    public static com.google.protobuf.Parser<CreditCardTransaction> PARSER =
        new com.google.protobuf.AbstractParser<CreditCardTransaction>() {
      public CreditCardTransaction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreditCardTransaction(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CreditCardTransaction> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .com.packt.masteringakka.bookstore.credit.CreditCardInfo cardInfo = 2;
    public static final int CARDINFO_FIELD_NUMBER = 2;
    private com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo cardInfo_;
    /**
     * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardInfo cardInfo = 2;</code>
     */
    public boolean hasCardInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardInfo cardInfo = 2;</code>
     */
    public com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo getCardInfo() {
      return cardInfo_;
    }
    /**
     * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardInfo cardInfo = 2;</code>
     */
    public com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfoOrBuilder getCardInfoOrBuilder() {
      return cardInfo_;
    }

    // required double amount = 3;
    public static final int AMOUNT_FIELD_NUMBER = 3;
    private double amount_;
    /**
     * <code>required double amount = 3;</code>
     */
    public boolean hasAmount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double amount = 3;</code>
     */
    public double getAmount() {
      return amount_;
    }

    // required string status = 4;
    public static final int STATUS_FIELD_NUMBER = 4;
    private java.lang.Object status_;
    /**
     * <code>required string status = 4;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string status = 4;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          status_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string status = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string confirmationCode = 5;
    public static final int CONFIRMATIONCODE_FIELD_NUMBER = 5;
    private java.lang.Object confirmationCode_;
    /**
     * <code>optional string confirmationCode = 5;</code>
     */
    public boolean hasConfirmationCode() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string confirmationCode = 5;</code>
     */
    public java.lang.String getConfirmationCode() {
      java.lang.Object ref = confirmationCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          confirmationCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string confirmationCode = 5;</code>
     */
    public com.google.protobuf.ByteString
        getConfirmationCodeBytes() {
      java.lang.Object ref = confirmationCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        confirmationCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 createTs = 6;
    public static final int CREATETS_FIELD_NUMBER = 6;
    private long createTs_;
    /**
     * <code>required int64 createTs = 6;</code>
     */
    public boolean hasCreateTs() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int64 createTs = 6;</code>
     */
    public long getCreateTs() {
      return createTs_;
    }

    private void initFields() {
      id_ = "";
      cardInfo_ = com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo.getDefaultInstance();
      amount_ = 0D;
      status_ = "";
      confirmationCode_ = "";
      createTs_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCardInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAmount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreateTs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getCardInfo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, cardInfo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, amount_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getStatusBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getConfirmationCodeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, createTs_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, cardInfo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, amount_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getStatusBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getConfirmationCodeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, createTs_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.packt.masteringakka.bookstore.credit.CreditCardTransaction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransactionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.packt.masteringakka.bookstore.credit.Datamodel.internal_static_com_packt_masteringakka_bookstore_credit_CreditCardTransaction_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.packt.masteringakka.bookstore.credit.Datamodel.internal_static_com_packt_masteringakka_bookstore_credit_CreditCardTransaction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction.class, com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction.Builder.class);
      }

      // Construct using com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCardInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (cardInfoBuilder_ == null) {
          cardInfo_ = com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo.getDefaultInstance();
        } else {
          cardInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        amount_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        confirmationCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        createTs_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.packt.masteringakka.bookstore.credit.Datamodel.internal_static_com_packt_masteringakka_bookstore_credit_CreditCardTransaction_descriptor;
      }

      public com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction getDefaultInstanceForType() {
        return com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction.getDefaultInstance();
      }

      public com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction build() {
        com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction buildPartial() {
        com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction result = new com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (cardInfoBuilder_ == null) {
          result.cardInfo_ = cardInfo_;
        } else {
          result.cardInfo_ = cardInfoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.amount_ = amount_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.confirmationCode_ = confirmationCode_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.createTs_ = createTs_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction) {
          return mergeFrom((com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction other) {
        if (other == com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasCardInfo()) {
          mergeCardInfo(other.getCardInfo());
        }
        if (other.hasAmount()) {
          setAmount(other.getAmount());
        }
        if (other.hasStatus()) {
          bitField0_ |= 0x00000008;
          status_ = other.status_;
          onChanged();
        }
        if (other.hasConfirmationCode()) {
          bitField0_ |= 0x00000010;
          confirmationCode_ = other.confirmationCode_;
          onChanged();
        }
        if (other.hasCreateTs()) {
          setCreateTs(other.getCreateTs());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasCardInfo()) {
          
          return false;
        }
        if (!hasAmount()) {
          
          return false;
        }
        if (!hasStatus()) {
          
          return false;
        }
        if (!hasCreateTs()) {
          
          return false;
        }
        if (!getCardInfo().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string id = 1;
      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      // required .com.packt.masteringakka.bookstore.credit.CreditCardInfo cardInfo = 2;
      private com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo cardInfo_ = com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo, com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo.Builder, com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfoOrBuilder> cardInfoBuilder_;
      /**
       * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardInfo cardInfo = 2;</code>
       */
      public boolean hasCardInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardInfo cardInfo = 2;</code>
       */
      public com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo getCardInfo() {
        if (cardInfoBuilder_ == null) {
          return cardInfo_;
        } else {
          return cardInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardInfo cardInfo = 2;</code>
       */
      public Builder setCardInfo(com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo value) {
        if (cardInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cardInfo_ = value;
          onChanged();
        } else {
          cardInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardInfo cardInfo = 2;</code>
       */
      public Builder setCardInfo(
          com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo.Builder builderForValue) {
        if (cardInfoBuilder_ == null) {
          cardInfo_ = builderForValue.build();
          onChanged();
        } else {
          cardInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardInfo cardInfo = 2;</code>
       */
      public Builder mergeCardInfo(com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo value) {
        if (cardInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              cardInfo_ != com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo.getDefaultInstance()) {
            cardInfo_ =
              com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo.newBuilder(cardInfo_).mergeFrom(value).buildPartial();
          } else {
            cardInfo_ = value;
          }
          onChanged();
        } else {
          cardInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardInfo cardInfo = 2;</code>
       */
      public Builder clearCardInfo() {
        if (cardInfoBuilder_ == null) {
          cardInfo_ = com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo.getDefaultInstance();
          onChanged();
        } else {
          cardInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardInfo cardInfo = 2;</code>
       */
      public com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo.Builder getCardInfoBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getCardInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardInfo cardInfo = 2;</code>
       */
      public com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfoOrBuilder getCardInfoOrBuilder() {
        if (cardInfoBuilder_ != null) {
          return cardInfoBuilder_.getMessageOrBuilder();
        } else {
          return cardInfo_;
        }
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardInfo cardInfo = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo, com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo.Builder, com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfoOrBuilder> 
          getCardInfoFieldBuilder() {
        if (cardInfoBuilder_ == null) {
          cardInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo, com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfo.Builder, com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardInfoOrBuilder>(
                  cardInfo_,
                  getParentForChildren(),
                  isClean());
          cardInfo_ = null;
        }
        return cardInfoBuilder_;
      }

      // required double amount = 3;
      private double amount_ ;
      /**
       * <code>required double amount = 3;</code>
       */
      public boolean hasAmount() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double amount = 3;</code>
       */
      public double getAmount() {
        return amount_;
      }
      /**
       * <code>required double amount = 3;</code>
       */
      public Builder setAmount(double value) {
        bitField0_ |= 0x00000004;
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double amount = 3;</code>
       */
      public Builder clearAmount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        amount_ = 0D;
        onChanged();
        return this;
      }

      // required string status = 4;
      private java.lang.Object status_ = "";
      /**
       * <code>required string status = 4;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string status = 4;</code>
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string status = 4;</code>
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string status = 4;</code>
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string status = 4;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <code>required string status = 4;</code>
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        status_ = value;
        onChanged();
        return this;
      }

      // optional string confirmationCode = 5;
      private java.lang.Object confirmationCode_ = "";
      /**
       * <code>optional string confirmationCode = 5;</code>
       */
      public boolean hasConfirmationCode() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string confirmationCode = 5;</code>
       */
      public java.lang.String getConfirmationCode() {
        java.lang.Object ref = confirmationCode_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          confirmationCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string confirmationCode = 5;</code>
       */
      public com.google.protobuf.ByteString
          getConfirmationCodeBytes() {
        java.lang.Object ref = confirmationCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          confirmationCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string confirmationCode = 5;</code>
       */
      public Builder setConfirmationCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        confirmationCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string confirmationCode = 5;</code>
       */
      public Builder clearConfirmationCode() {
        bitField0_ = (bitField0_ & ~0x00000010);
        confirmationCode_ = getDefaultInstance().getConfirmationCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string confirmationCode = 5;</code>
       */
      public Builder setConfirmationCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        confirmationCode_ = value;
        onChanged();
        return this;
      }

      // required int64 createTs = 6;
      private long createTs_ ;
      /**
       * <code>required int64 createTs = 6;</code>
       */
      public boolean hasCreateTs() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int64 createTs = 6;</code>
       */
      public long getCreateTs() {
        return createTs_;
      }
      /**
       * <code>required int64 createTs = 6;</code>
       */
      public Builder setCreateTs(long value) {
        bitField0_ |= 0x00000020;
        createTs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 createTs = 6;</code>
       */
      public Builder clearCreateTs() {
        bitField0_ = (bitField0_ & ~0x00000020);
        createTs_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.packt.masteringakka.bookstore.credit.CreditCardTransaction)
    }

    static {
      defaultInstance = new CreditCardTransaction(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.packt.masteringakka.bookstore.credit.CreditCardTransaction)
  }

  public interface CreditTransactionCreatedOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.packt.masteringakka.bookstore.credit.CreditCardTransaction txn = 1;
    /**
     * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardTransaction txn = 1;</code>
     */
    boolean hasTxn();
    /**
     * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardTransaction txn = 1;</code>
     */
    com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction getTxn();
    /**
     * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardTransaction txn = 1;</code>
     */
    com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransactionOrBuilder getTxnOrBuilder();
  }
  /**
   * Protobuf type {@code com.packt.masteringakka.bookstore.credit.CreditTransactionCreated}
   */
  public static final class CreditTransactionCreated extends
      com.google.protobuf.GeneratedMessage
      implements CreditTransactionCreatedOrBuilder {
    // Use CreditTransactionCreated.newBuilder() to construct.
    private CreditTransactionCreated(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CreditTransactionCreated(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CreditTransactionCreated defaultInstance;
    public static CreditTransactionCreated getDefaultInstance() {
      return defaultInstance;
    }

    public CreditTransactionCreated getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CreditTransactionCreated(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = txn_.toBuilder();
              }
              txn_ = input.readMessage(com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(txn_);
                txn_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.packt.masteringakka.bookstore.credit.Datamodel.internal_static_com_packt_masteringakka_bookstore_credit_CreditTransactionCreated_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.packt.masteringakka.bookstore.credit.Datamodel.internal_static_com_packt_masteringakka_bookstore_credit_CreditTransactionCreated_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated.class, com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated.Builder.class);
    }

    public static com.google.protobuf.Parser<CreditTransactionCreated> PARSER =
        new com.google.protobuf.AbstractParser<CreditTransactionCreated>() {
      public CreditTransactionCreated parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreditTransactionCreated(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CreditTransactionCreated> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.packt.masteringakka.bookstore.credit.CreditCardTransaction txn = 1;
    public static final int TXN_FIELD_NUMBER = 1;
    private com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction txn_;
    /**
     * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardTransaction txn = 1;</code>
     */
    public boolean hasTxn() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardTransaction txn = 1;</code>
     */
    public com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction getTxn() {
      return txn_;
    }
    /**
     * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardTransaction txn = 1;</code>
     */
    public com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransactionOrBuilder getTxnOrBuilder() {
      return txn_;
    }

    private void initFields() {
      txn_ = com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTxn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getTxn().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, txn_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, txn_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.packt.masteringakka.bookstore.credit.CreditTransactionCreated}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreatedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.packt.masteringakka.bookstore.credit.Datamodel.internal_static_com_packt_masteringakka_bookstore_credit_CreditTransactionCreated_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.packt.masteringakka.bookstore.credit.Datamodel.internal_static_com_packt_masteringakka_bookstore_credit_CreditTransactionCreated_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated.class, com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated.Builder.class);
      }

      // Construct using com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTxnFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (txnBuilder_ == null) {
          txn_ = com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction.getDefaultInstance();
        } else {
          txnBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.packt.masteringakka.bookstore.credit.Datamodel.internal_static_com_packt_masteringakka_bookstore_credit_CreditTransactionCreated_descriptor;
      }

      public com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated getDefaultInstanceForType() {
        return com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated.getDefaultInstance();
      }

      public com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated build() {
        com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated buildPartial() {
        com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated result = new com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (txnBuilder_ == null) {
          result.txn_ = txn_;
        } else {
          result.txn_ = txnBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated) {
          return mergeFrom((com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated other) {
        if (other == com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated.getDefaultInstance()) return this;
        if (other.hasTxn()) {
          mergeTxn(other.getTxn());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTxn()) {
          
          return false;
        }
        if (!getTxn().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.packt.masteringakka.bookstore.credit.Datamodel.CreditTransactionCreated) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.packt.masteringakka.bookstore.credit.CreditCardTransaction txn = 1;
      private com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction txn_ = com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction, com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction.Builder, com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransactionOrBuilder> txnBuilder_;
      /**
       * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardTransaction txn = 1;</code>
       */
      public boolean hasTxn() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardTransaction txn = 1;</code>
       */
      public com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction getTxn() {
        if (txnBuilder_ == null) {
          return txn_;
        } else {
          return txnBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardTransaction txn = 1;</code>
       */
      public Builder setTxn(com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction value) {
        if (txnBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          txn_ = value;
          onChanged();
        } else {
          txnBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardTransaction txn = 1;</code>
       */
      public Builder setTxn(
          com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction.Builder builderForValue) {
        if (txnBuilder_ == null) {
          txn_ = builderForValue.build();
          onChanged();
        } else {
          txnBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardTransaction txn = 1;</code>
       */
      public Builder mergeTxn(com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction value) {
        if (txnBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              txn_ != com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction.getDefaultInstance()) {
            txn_ =
              com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction.newBuilder(txn_).mergeFrom(value).buildPartial();
          } else {
            txn_ = value;
          }
          onChanged();
        } else {
          txnBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardTransaction txn = 1;</code>
       */
      public Builder clearTxn() {
        if (txnBuilder_ == null) {
          txn_ = com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction.getDefaultInstance();
          onChanged();
        } else {
          txnBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardTransaction txn = 1;</code>
       */
      public com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction.Builder getTxnBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getTxnFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardTransaction txn = 1;</code>
       */
      public com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransactionOrBuilder getTxnOrBuilder() {
        if (txnBuilder_ != null) {
          return txnBuilder_.getMessageOrBuilder();
        } else {
          return txn_;
        }
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.credit.CreditCardTransaction txn = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction, com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction.Builder, com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransactionOrBuilder> 
          getTxnFieldBuilder() {
        if (txnBuilder_ == null) {
          txnBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction, com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransaction.Builder, com.packt.masteringakka.bookstore.credit.Datamodel.CreditCardTransactionOrBuilder>(
                  txn_,
                  getParentForChildren(),
                  isClean());
          txn_ = null;
        }
        return txnBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.packt.masteringakka.bookstore.credit.CreditTransactionCreated)
    }

    static {
      defaultInstance = new CreditTransactionCreated(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.packt.masteringakka.bookstore.credit.CreditTransactionCreated)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packt_masteringakka_bookstore_credit_CreditCardInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_packt_masteringakka_bookstore_credit_CreditCardInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packt_masteringakka_bookstore_credit_CreditCardTransaction_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_packt_masteringakka_bookstore_credit_CreditCardTransaction_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packt_masteringakka_bookstore_credit_CreditTransactionCreated_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_packt_masteringakka_bookstore_credit_CreditTransactionCreated_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036src/main/proto/datamodel.proto\022(com.pa" +
      "ckt.masteringakka.bookstore.credit\"^\n\016Cr" +
      "editCardInfo\022\022\n\ncardHolder\030\001 \002(\t\022\020\n\010card" +
      "Type\030\002 \002(\t\022\022\n\ncardNumber\030\003 \002(\t\022\022\n\nexpira" +
      "tion\030\004 \002(\003\"\273\001\n\025CreditCardTransaction\022\n\n\002" +
      "id\030\001 \002(\t\022J\n\010cardInfo\030\002 \002(\01328.com.packt.m" +
      "asteringakka.bookstore.credit.CreditCard" +
      "Info\022\016\n\006amount\030\003 \002(\001\022\016\n\006status\030\004 \002(\t\022\030\n\020" +
      "confirmationCode\030\005 \001(\t\022\020\n\010createTs\030\006 \002(\003" +
      "\"h\n\030CreditTransactionCreated\022L\n\003txn\030\001 \002(",
      "\0132?.com.packt.masteringakka.bookstore.cr" +
      "edit.CreditCardTransactionB\rB\tDatamodelH" +
      "\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_packt_masteringakka_bookstore_credit_CreditCardInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_packt_masteringakka_bookstore_credit_CreditCardInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_packt_masteringakka_bookstore_credit_CreditCardInfo_descriptor,
              new java.lang.String[] { "CardHolder", "CardType", "CardNumber", "Expiration", });
          internal_static_com_packt_masteringakka_bookstore_credit_CreditCardTransaction_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_packt_masteringakka_bookstore_credit_CreditCardTransaction_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_packt_masteringakka_bookstore_credit_CreditCardTransaction_descriptor,
              new java.lang.String[] { "Id", "CardInfo", "Amount", "Status", "ConfirmationCode", "CreateTs", });
          internal_static_com_packt_masteringakka_bookstore_credit_CreditTransactionCreated_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_packt_masteringakka_bookstore_credit_CreditTransactionCreated_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_packt_masteringakka_bookstore_credit_CreditTransactionCreated_descriptor,
              new java.lang.String[] { "Txn", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
