// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/datamodel.proto

package com.packt.masteringakka.bookstore.user;

public final class Datamodel {
  private Datamodel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BookstoreUserOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string email = 1;
    /**
     * <code>required string email = 1;</code>
     */
    boolean hasEmail();
    /**
     * <code>required string email = 1;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>required string email = 1;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    // required string firstName = 2;
    /**
     * <code>required string firstName = 2;</code>
     */
    boolean hasFirstName();
    /**
     * <code>required string firstName = 2;</code>
     */
    java.lang.String getFirstName();
    /**
     * <code>required string firstName = 2;</code>
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    // required string lastName = 3;
    /**
     * <code>required string lastName = 3;</code>
     */
    boolean hasLastName();
    /**
     * <code>required string lastName = 3;</code>
     */
    java.lang.String getLastName();
    /**
     * <code>required string lastName = 3;</code>
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    // required int64 createTs = 4;
    /**
     * <code>required int64 createTs = 4;</code>
     */
    boolean hasCreateTs();
    /**
     * <code>required int64 createTs = 4;</code>
     */
    long getCreateTs();

    // required bool deleted = 5;
    /**
     * <code>required bool deleted = 5;</code>
     */
    boolean hasDeleted();
    /**
     * <code>required bool deleted = 5;</code>
     */
    boolean getDeleted();
  }
  /**
   * Protobuf type {@code com.packt.masteringakka.bookstore.user.BookstoreUser}
   */
  public static final class BookstoreUser extends
      com.google.protobuf.GeneratedMessage
      implements BookstoreUserOrBuilder {
    // Use BookstoreUser.newBuilder() to construct.
    private BookstoreUser(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BookstoreUser(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BookstoreUser defaultInstance;
    public static BookstoreUser getDefaultInstance() {
      return defaultInstance;
    }

    public BookstoreUser getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BookstoreUser(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              email_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              firstName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              lastName_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              createTs_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              deleted_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.packt.masteringakka.bookstore.user.Datamodel.internal_static_com_packt_masteringakka_bookstore_user_BookstoreUser_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.packt.masteringakka.bookstore.user.Datamodel.internal_static_com_packt_masteringakka_bookstore_user_BookstoreUser_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser.class, com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser.Builder.class);
    }

    public static com.google.protobuf.Parser<BookstoreUser> PARSER =
        new com.google.protobuf.AbstractParser<BookstoreUser>() {
      public BookstoreUser parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BookstoreUser(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BookstoreUser> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string email = 1;
    public static final int EMAIL_FIELD_NUMBER = 1;
    private java.lang.Object email_;
    /**
     * <code>required string email = 1;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string email = 1;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string email = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string firstName = 2;
    public static final int FIRSTNAME_FIELD_NUMBER = 2;
    private java.lang.Object firstName_;
    /**
     * <code>required string firstName = 2;</code>
     */
    public boolean hasFirstName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string firstName = 2;</code>
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          firstName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string firstName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string lastName = 3;
    public static final int LASTNAME_FIELD_NUMBER = 3;
    private java.lang.Object lastName_;
    /**
     * <code>required string lastName = 3;</code>
     */
    public boolean hasLastName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string lastName = 3;</code>
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lastName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string lastName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 createTs = 4;
    public static final int CREATETS_FIELD_NUMBER = 4;
    private long createTs_;
    /**
     * <code>required int64 createTs = 4;</code>
     */
    public boolean hasCreateTs() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 createTs = 4;</code>
     */
    public long getCreateTs() {
      return createTs_;
    }

    // required bool deleted = 5;
    public static final int DELETED_FIELD_NUMBER = 5;
    private boolean deleted_;
    /**
     * <code>required bool deleted = 5;</code>
     */
    public boolean hasDeleted() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bool deleted = 5;</code>
     */
    public boolean getDeleted() {
      return deleted_;
    }

    private void initFields() {
      email_ = "";
      firstName_ = "";
      lastName_ = "";
      createTs_ = 0L;
      deleted_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasEmail()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFirstName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLastName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreateTs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDeleted()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getEmailBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFirstNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLastNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, createTs_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, deleted_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getEmailBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFirstNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLastNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, createTs_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, deleted_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.packt.masteringakka.bookstore.user.BookstoreUser}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.packt.masteringakka.bookstore.user.Datamodel.internal_static_com_packt_masteringakka_bookstore_user_BookstoreUser_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.packt.masteringakka.bookstore.user.Datamodel.internal_static_com_packt_masteringakka_bookstore_user_BookstoreUser_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser.class, com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser.Builder.class);
      }

      // Construct using com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        firstName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        lastName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        createTs_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        deleted_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.packt.masteringakka.bookstore.user.Datamodel.internal_static_com_packt_masteringakka_bookstore_user_BookstoreUser_descriptor;
      }

      public com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser getDefaultInstanceForType() {
        return com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser.getDefaultInstance();
      }

      public com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser build() {
        com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser buildPartial() {
        com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser result = new com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.email_ = email_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.firstName_ = firstName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.lastName_ = lastName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.createTs_ = createTs_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.deleted_ = deleted_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser) {
          return mergeFrom((com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser other) {
        if (other == com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser.getDefaultInstance()) return this;
        if (other.hasEmail()) {
          bitField0_ |= 0x00000001;
          email_ = other.email_;
          onChanged();
        }
        if (other.hasFirstName()) {
          bitField0_ |= 0x00000002;
          firstName_ = other.firstName_;
          onChanged();
        }
        if (other.hasLastName()) {
          bitField0_ |= 0x00000004;
          lastName_ = other.lastName_;
          onChanged();
        }
        if (other.hasCreateTs()) {
          setCreateTs(other.getCreateTs());
        }
        if (other.hasDeleted()) {
          setDeleted(other.getDeleted());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEmail()) {
          
          return false;
        }
        if (!hasFirstName()) {
          
          return false;
        }
        if (!hasLastName()) {
          
          return false;
        }
        if (!hasCreateTs()) {
          
          return false;
        }
        if (!hasDeleted()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string email = 1;
      private java.lang.Object email_ = "";
      /**
       * <code>required string email = 1;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string email = 1;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string email = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string email = 1;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string email = 1;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000001);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>required string email = 1;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        email_ = value;
        onChanged();
        return this;
      }

      // required string firstName = 2;
      private java.lang.Object firstName_ = "";
      /**
       * <code>required string firstName = 2;</code>
       */
      public boolean hasFirstName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string firstName = 2;</code>
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string firstName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string firstName = 2;</code>
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string firstName = 2;</code>
       */
      public Builder clearFirstName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>required string firstName = 2;</code>
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        firstName_ = value;
        onChanged();
        return this;
      }

      // required string lastName = 3;
      private java.lang.Object lastName_ = "";
      /**
       * <code>required string lastName = 3;</code>
       */
      public boolean hasLastName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string lastName = 3;</code>
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string lastName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string lastName = 3;</code>
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string lastName = 3;</code>
       */
      public Builder clearLastName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>required string lastName = 3;</code>
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        lastName_ = value;
        onChanged();
        return this;
      }

      // required int64 createTs = 4;
      private long createTs_ ;
      /**
       * <code>required int64 createTs = 4;</code>
       */
      public boolean hasCreateTs() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 createTs = 4;</code>
       */
      public long getCreateTs() {
        return createTs_;
      }
      /**
       * <code>required int64 createTs = 4;</code>
       */
      public Builder setCreateTs(long value) {
        bitField0_ |= 0x00000008;
        createTs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 createTs = 4;</code>
       */
      public Builder clearCreateTs() {
        bitField0_ = (bitField0_ & ~0x00000008);
        createTs_ = 0L;
        onChanged();
        return this;
      }

      // required bool deleted = 5;
      private boolean deleted_ ;
      /**
       * <code>required bool deleted = 5;</code>
       */
      public boolean hasDeleted() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bool deleted = 5;</code>
       */
      public boolean getDeleted() {
        return deleted_;
      }
      /**
       * <code>required bool deleted = 5;</code>
       */
      public Builder setDeleted(boolean value) {
        bitField0_ |= 0x00000010;
        deleted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool deleted = 5;</code>
       */
      public Builder clearDeleted() {
        bitField0_ = (bitField0_ & ~0x00000010);
        deleted_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.packt.masteringakka.bookstore.user.BookstoreUser)
    }

    static {
      defaultInstance = new BookstoreUser(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.packt.masteringakka.bookstore.user.BookstoreUser)
  }

  public interface UserCreatedOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.packt.masteringakka.bookstore.user.BookstoreUser user = 1;
    /**
     * <code>required .com.packt.masteringakka.bookstore.user.BookstoreUser user = 1;</code>
     */
    boolean hasUser();
    /**
     * <code>required .com.packt.masteringakka.bookstore.user.BookstoreUser user = 1;</code>
     */
    com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser getUser();
    /**
     * <code>required .com.packt.masteringakka.bookstore.user.BookstoreUser user = 1;</code>
     */
    com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUserOrBuilder getUserOrBuilder();
  }
  /**
   * Protobuf type {@code com.packt.masteringakka.bookstore.user.UserCreated}
   */
  public static final class UserCreated extends
      com.google.protobuf.GeneratedMessage
      implements UserCreatedOrBuilder {
    // Use UserCreated.newBuilder() to construct.
    private UserCreated(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UserCreated(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UserCreated defaultInstance;
    public static UserCreated getDefaultInstance() {
      return defaultInstance;
    }

    public UserCreated getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UserCreated(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = user_.toBuilder();
              }
              user_ = input.readMessage(com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user_);
                user_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.packt.masteringakka.bookstore.user.Datamodel.internal_static_com_packt_masteringakka_bookstore_user_UserCreated_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.packt.masteringakka.bookstore.user.Datamodel.internal_static_com_packt_masteringakka_bookstore_user_UserCreated_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.packt.masteringakka.bookstore.user.Datamodel.UserCreated.class, com.packt.masteringakka.bookstore.user.Datamodel.UserCreated.Builder.class);
    }

    public static com.google.protobuf.Parser<UserCreated> PARSER =
        new com.google.protobuf.AbstractParser<UserCreated>() {
      public UserCreated parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserCreated(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UserCreated> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.packt.masteringakka.bookstore.user.BookstoreUser user = 1;
    public static final int USER_FIELD_NUMBER = 1;
    private com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser user_;
    /**
     * <code>required .com.packt.masteringakka.bookstore.user.BookstoreUser user = 1;</code>
     */
    public boolean hasUser() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.packt.masteringakka.bookstore.user.BookstoreUser user = 1;</code>
     */
    public com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser getUser() {
      return user_;
    }
    /**
     * <code>required .com.packt.masteringakka.bookstore.user.BookstoreUser user = 1;</code>
     */
    public com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUserOrBuilder getUserOrBuilder() {
      return user_;
    }

    private void initFields() {
      user_ = com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUser()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getUser().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, user_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, user_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.packt.masteringakka.bookstore.user.Datamodel.UserCreated parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.UserCreated parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.UserCreated parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.UserCreated parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.UserCreated parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.UserCreated parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.UserCreated parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.UserCreated parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.UserCreated parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.UserCreated parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.packt.masteringakka.bookstore.user.Datamodel.UserCreated prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.packt.masteringakka.bookstore.user.UserCreated}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.packt.masteringakka.bookstore.user.Datamodel.UserCreatedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.packt.masteringakka.bookstore.user.Datamodel.internal_static_com_packt_masteringakka_bookstore_user_UserCreated_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.packt.masteringakka.bookstore.user.Datamodel.internal_static_com_packt_masteringakka_bookstore_user_UserCreated_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.packt.masteringakka.bookstore.user.Datamodel.UserCreated.class, com.packt.masteringakka.bookstore.user.Datamodel.UserCreated.Builder.class);
      }

      // Construct using com.packt.masteringakka.bookstore.user.Datamodel.UserCreated.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUserFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (userBuilder_ == null) {
          user_ = com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser.getDefaultInstance();
        } else {
          userBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.packt.masteringakka.bookstore.user.Datamodel.internal_static_com_packt_masteringakka_bookstore_user_UserCreated_descriptor;
      }

      public com.packt.masteringakka.bookstore.user.Datamodel.UserCreated getDefaultInstanceForType() {
        return com.packt.masteringakka.bookstore.user.Datamodel.UserCreated.getDefaultInstance();
      }

      public com.packt.masteringakka.bookstore.user.Datamodel.UserCreated build() {
        com.packt.masteringakka.bookstore.user.Datamodel.UserCreated result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.packt.masteringakka.bookstore.user.Datamodel.UserCreated buildPartial() {
        com.packt.masteringakka.bookstore.user.Datamodel.UserCreated result = new com.packt.masteringakka.bookstore.user.Datamodel.UserCreated(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.packt.masteringakka.bookstore.user.Datamodel.UserCreated) {
          return mergeFrom((com.packt.masteringakka.bookstore.user.Datamodel.UserCreated)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.packt.masteringakka.bookstore.user.Datamodel.UserCreated other) {
        if (other == com.packt.masteringakka.bookstore.user.Datamodel.UserCreated.getDefaultInstance()) return this;
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUser()) {
          
          return false;
        }
        if (!getUser().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.packt.masteringakka.bookstore.user.Datamodel.UserCreated parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.packt.masteringakka.bookstore.user.Datamodel.UserCreated) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.packt.masteringakka.bookstore.user.BookstoreUser user = 1;
      private com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser user_ = com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser, com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser.Builder, com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUserOrBuilder> userBuilder_;
      /**
       * <code>required .com.packt.masteringakka.bookstore.user.BookstoreUser user = 1;</code>
       */
      public boolean hasUser() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.user.BookstoreUser user = 1;</code>
       */
      public com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser getUser() {
        if (userBuilder_ == null) {
          return user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.user.BookstoreUser user = 1;</code>
       */
      public Builder setUser(com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.user.BookstoreUser user = 1;</code>
       */
      public Builder setUser(
          com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.user.BookstoreUser user = 1;</code>
       */
      public Builder mergeUser(com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser value) {
        if (userBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              user_ != com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser.getDefaultInstance()) {
            user_ =
              com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.user.BookstoreUser user = 1;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser.getDefaultInstance();
          onChanged();
        } else {
          userBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.user.BookstoreUser user = 1;</code>
       */
      public com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser.Builder getUserBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.user.BookstoreUser user = 1;</code>
       */
      public com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUserOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_;
        }
      }
      /**
       * <code>required .com.packt.masteringakka.bookstore.user.BookstoreUser user = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser, com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser.Builder, com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUserOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser, com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUser.Builder, com.packt.masteringakka.bookstore.user.Datamodel.BookstoreUserOrBuilder>(
                  user_,
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.packt.masteringakka.bookstore.user.UserCreated)
    }

    static {
      defaultInstance = new UserCreated(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.packt.masteringakka.bookstore.user.UserCreated)
  }

  public interface PersonalInfoUpdatedOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string firstName = 1;
    /**
     * <code>required string firstName = 1;</code>
     */
    boolean hasFirstName();
    /**
     * <code>required string firstName = 1;</code>
     */
    java.lang.String getFirstName();
    /**
     * <code>required string firstName = 1;</code>
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    // required string lastName = 2;
    /**
     * <code>required string lastName = 2;</code>
     */
    boolean hasLastName();
    /**
     * <code>required string lastName = 2;</code>
     */
    java.lang.String getLastName();
    /**
     * <code>required string lastName = 2;</code>
     */
    com.google.protobuf.ByteString
        getLastNameBytes();
  }
  /**
   * Protobuf type {@code com.packt.masteringakka.bookstore.user.PersonalInfoUpdated}
   */
  public static final class PersonalInfoUpdated extends
      com.google.protobuf.GeneratedMessage
      implements PersonalInfoUpdatedOrBuilder {
    // Use PersonalInfoUpdated.newBuilder() to construct.
    private PersonalInfoUpdated(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PersonalInfoUpdated(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PersonalInfoUpdated defaultInstance;
    public static PersonalInfoUpdated getDefaultInstance() {
      return defaultInstance;
    }

    public PersonalInfoUpdated getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PersonalInfoUpdated(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              firstName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              lastName_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.packt.masteringakka.bookstore.user.Datamodel.internal_static_com_packt_masteringakka_bookstore_user_PersonalInfoUpdated_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.packt.masteringakka.bookstore.user.Datamodel.internal_static_com_packt_masteringakka_bookstore_user_PersonalInfoUpdated_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated.class, com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated.Builder.class);
    }

    public static com.google.protobuf.Parser<PersonalInfoUpdated> PARSER =
        new com.google.protobuf.AbstractParser<PersonalInfoUpdated>() {
      public PersonalInfoUpdated parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PersonalInfoUpdated(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PersonalInfoUpdated> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string firstName = 1;
    public static final int FIRSTNAME_FIELD_NUMBER = 1;
    private java.lang.Object firstName_;
    /**
     * <code>required string firstName = 1;</code>
     */
    public boolean hasFirstName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string firstName = 1;</code>
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          firstName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string firstName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string lastName = 2;
    public static final int LASTNAME_FIELD_NUMBER = 2;
    private java.lang.Object lastName_;
    /**
     * <code>required string lastName = 2;</code>
     */
    public boolean hasLastName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string lastName = 2;</code>
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lastName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string lastName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      firstName_ = "";
      lastName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFirstName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLastName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFirstNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLastNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFirstNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLastNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.packt.masteringakka.bookstore.user.PersonalInfoUpdated}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdatedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.packt.masteringakka.bookstore.user.Datamodel.internal_static_com_packt_masteringakka_bookstore_user_PersonalInfoUpdated_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.packt.masteringakka.bookstore.user.Datamodel.internal_static_com_packt_masteringakka_bookstore_user_PersonalInfoUpdated_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated.class, com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated.Builder.class);
      }

      // Construct using com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        firstName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        lastName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.packt.masteringakka.bookstore.user.Datamodel.internal_static_com_packt_masteringakka_bookstore_user_PersonalInfoUpdated_descriptor;
      }

      public com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated getDefaultInstanceForType() {
        return com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated.getDefaultInstance();
      }

      public com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated build() {
        com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated buildPartial() {
        com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated result = new com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.firstName_ = firstName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lastName_ = lastName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated) {
          return mergeFrom((com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated other) {
        if (other == com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated.getDefaultInstance()) return this;
        if (other.hasFirstName()) {
          bitField0_ |= 0x00000001;
          firstName_ = other.firstName_;
          onChanged();
        }
        if (other.hasLastName()) {
          bitField0_ |= 0x00000002;
          lastName_ = other.lastName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFirstName()) {
          
          return false;
        }
        if (!hasLastName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.packt.masteringakka.bookstore.user.Datamodel.PersonalInfoUpdated) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string firstName = 1;
      private java.lang.Object firstName_ = "";
      /**
       * <code>required string firstName = 1;</code>
       */
      public boolean hasFirstName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string firstName = 1;</code>
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string firstName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string firstName = 1;</code>
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string firstName = 1;</code>
       */
      public Builder clearFirstName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>required string firstName = 1;</code>
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        firstName_ = value;
        onChanged();
        return this;
      }

      // required string lastName = 2;
      private java.lang.Object lastName_ = "";
      /**
       * <code>required string lastName = 2;</code>
       */
      public boolean hasLastName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string lastName = 2;</code>
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string lastName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string lastName = 2;</code>
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string lastName = 2;</code>
       */
      public Builder clearLastName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>required string lastName = 2;</code>
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        lastName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.packt.masteringakka.bookstore.user.PersonalInfoUpdated)
    }

    static {
      defaultInstance = new PersonalInfoUpdated(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.packt.masteringakka.bookstore.user.PersonalInfoUpdated)
  }

  public interface UserDeletedOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string email = 1;
    /**
     * <code>required string email = 1;</code>
     */
    boolean hasEmail();
    /**
     * <code>required string email = 1;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>required string email = 1;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();
  }
  /**
   * Protobuf type {@code com.packt.masteringakka.bookstore.user.UserDeleted}
   */
  public static final class UserDeleted extends
      com.google.protobuf.GeneratedMessage
      implements UserDeletedOrBuilder {
    // Use UserDeleted.newBuilder() to construct.
    private UserDeleted(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UserDeleted(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UserDeleted defaultInstance;
    public static UserDeleted getDefaultInstance() {
      return defaultInstance;
    }

    public UserDeleted getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UserDeleted(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              email_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.packt.masteringakka.bookstore.user.Datamodel.internal_static_com_packt_masteringakka_bookstore_user_UserDeleted_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.packt.masteringakka.bookstore.user.Datamodel.internal_static_com_packt_masteringakka_bookstore_user_UserDeleted_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted.class, com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted.Builder.class);
    }

    public static com.google.protobuf.Parser<UserDeleted> PARSER =
        new com.google.protobuf.AbstractParser<UserDeleted>() {
      public UserDeleted parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserDeleted(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UserDeleted> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string email = 1;
    public static final int EMAIL_FIELD_NUMBER = 1;
    private java.lang.Object email_;
    /**
     * <code>required string email = 1;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string email = 1;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string email = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      email_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasEmail()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getEmailBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getEmailBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.packt.masteringakka.bookstore.user.UserDeleted}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.packt.masteringakka.bookstore.user.Datamodel.UserDeletedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.packt.masteringakka.bookstore.user.Datamodel.internal_static_com_packt_masteringakka_bookstore_user_UserDeleted_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.packt.masteringakka.bookstore.user.Datamodel.internal_static_com_packt_masteringakka_bookstore_user_UserDeleted_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted.class, com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted.Builder.class);
      }

      // Construct using com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.packt.masteringakka.bookstore.user.Datamodel.internal_static_com_packt_masteringakka_bookstore_user_UserDeleted_descriptor;
      }

      public com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted getDefaultInstanceForType() {
        return com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted.getDefaultInstance();
      }

      public com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted build() {
        com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted buildPartial() {
        com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted result = new com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.email_ = email_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted) {
          return mergeFrom((com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted other) {
        if (other == com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted.getDefaultInstance()) return this;
        if (other.hasEmail()) {
          bitField0_ |= 0x00000001;
          email_ = other.email_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEmail()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.packt.masteringakka.bookstore.user.Datamodel.UserDeleted) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string email = 1;
      private java.lang.Object email_ = "";
      /**
       * <code>required string email = 1;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string email = 1;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string email = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string email = 1;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string email = 1;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000001);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>required string email = 1;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        email_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.packt.masteringakka.bookstore.user.UserDeleted)
    }

    static {
      defaultInstance = new UserDeleted(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.packt.masteringakka.bookstore.user.UserDeleted)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packt_masteringakka_bookstore_user_BookstoreUser_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_packt_masteringakka_bookstore_user_BookstoreUser_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packt_masteringakka_bookstore_user_UserCreated_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_packt_masteringakka_bookstore_user_UserCreated_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packt_masteringakka_bookstore_user_PersonalInfoUpdated_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_packt_masteringakka_bookstore_user_PersonalInfoUpdated_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packt_masteringakka_bookstore_user_UserDeleted_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_packt_masteringakka_bookstore_user_UserDeleted_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036src/main/proto/datamodel.proto\022&com.pa" +
      "ckt.masteringakka.bookstore.user\"f\n\rBook" +
      "storeUser\022\r\n\005email\030\001 \002(\t\022\021\n\tfirstName\030\002 " +
      "\002(\t\022\020\n\010lastName\030\003 \002(\t\022\020\n\010createTs\030\004 \002(\003\022" +
      "\017\n\007deleted\030\005 \002(\010\"R\n\013UserCreated\022C\n\004user\030" +
      "\001 \002(\01325.com.packt.masteringakka.bookstor" +
      "e.user.BookstoreUser\":\n\023PersonalInfoUpda" +
      "ted\022\021\n\tfirstName\030\001 \002(\t\022\020\n\010lastName\030\002 \002(\t" +
      "\"\034\n\013UserDeleted\022\r\n\005email\030\001 \002(\tB\rB\tDatamo" +
      "delH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_packt_masteringakka_bookstore_user_BookstoreUser_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_packt_masteringakka_bookstore_user_BookstoreUser_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_packt_masteringakka_bookstore_user_BookstoreUser_descriptor,
              new java.lang.String[] { "Email", "FirstName", "LastName", "CreateTs", "Deleted", });
          internal_static_com_packt_masteringakka_bookstore_user_UserCreated_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_packt_masteringakka_bookstore_user_UserCreated_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_packt_masteringakka_bookstore_user_UserCreated_descriptor,
              new java.lang.String[] { "User", });
          internal_static_com_packt_masteringakka_bookstore_user_PersonalInfoUpdated_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_packt_masteringakka_bookstore_user_PersonalInfoUpdated_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_packt_masteringakka_bookstore_user_PersonalInfoUpdated_descriptor,
              new java.lang.String[] { "FirstName", "LastName", });
          internal_static_com_packt_masteringakka_bookstore_user_UserDeleted_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_packt_masteringakka_bookstore_user_UserDeleted_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_packt_masteringakka_bookstore_user_UserDeleted_descriptor,
              new java.lang.String[] { "Email", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
