// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/inventorydatamodel.proto

package com.packt.masteringakka.bookstore.inventory;

public final class Datamodel {
  private Datamodel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface InventoryAllocatedOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string orderId = 1;
    /**
     * <code>required string orderId = 1;</code>
     */
    boolean hasOrderId();
    /**
     * <code>required string orderId = 1;</code>
     */
    java.lang.String getOrderId();
    /**
     * <code>required string orderId = 1;</code>
     */
    com.google.protobuf.ByteString
        getOrderIdBytes();

    // required int32 amount = 2;
    /**
     * <code>required int32 amount = 2;</code>
     */
    boolean hasAmount();
    /**
     * <code>required int32 amount = 2;</code>
     */
    int getAmount();

    // required string bookId = 3;
    /**
     * <code>required string bookId = 3;</code>
     */
    boolean hasBookId();
    /**
     * <code>required string bookId = 3;</code>
     */
    java.lang.String getBookId();
    /**
     * <code>required string bookId = 3;</code>
     */
    com.google.protobuf.ByteString
        getBookIdBytes();
  }
  /**
   * Protobuf type {@code com.packt.masteringakka.bookstore.inventory.InventoryAllocated}
   */
  public static final class InventoryAllocated extends
      com.google.protobuf.GeneratedMessage
      implements InventoryAllocatedOrBuilder {
    // Use InventoryAllocated.newBuilder() to construct.
    private InventoryAllocated(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InventoryAllocated(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InventoryAllocated defaultInstance;
    public static InventoryAllocated getDefaultInstance() {
      return defaultInstance;
    }

    public InventoryAllocated getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InventoryAllocated(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              orderId_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              amount_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              bookId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.packt.masteringakka.bookstore.inventory.Datamodel.internal_static_com_packt_masteringakka_bookstore_inventory_InventoryAllocated_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.packt.masteringakka.bookstore.inventory.Datamodel.internal_static_com_packt_masteringakka_bookstore_inventory_InventoryAllocated_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated.class, com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated.Builder.class);
    }

    public static com.google.protobuf.Parser<InventoryAllocated> PARSER =
        new com.google.protobuf.AbstractParser<InventoryAllocated>() {
      public InventoryAllocated parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InventoryAllocated(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<InventoryAllocated> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string orderId = 1;
    public static final int ORDERID_FIELD_NUMBER = 1;
    private java.lang.Object orderId_;
    /**
     * <code>required string orderId = 1;</code>
     */
    public boolean hasOrderId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string orderId = 1;</code>
     */
    public java.lang.String getOrderId() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          orderId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string orderId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOrderIdBytes() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 amount = 2;
    public static final int AMOUNT_FIELD_NUMBER = 2;
    private int amount_;
    /**
     * <code>required int32 amount = 2;</code>
     */
    public boolean hasAmount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 amount = 2;</code>
     */
    public int getAmount() {
      return amount_;
    }

    // required string bookId = 3;
    public static final int BOOKID_FIELD_NUMBER = 3;
    private java.lang.Object bookId_;
    /**
     * <code>required string bookId = 3;</code>
     */
    public boolean hasBookId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string bookId = 3;</code>
     */
    public java.lang.String getBookId() {
      java.lang.Object ref = bookId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bookId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string bookId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBookIdBytes() {
      java.lang.Object ref = bookId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bookId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      orderId_ = "";
      amount_ = 0;
      bookId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasOrderId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAmount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBookId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getOrderIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, amount_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getBookIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getOrderIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, amount_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getBookIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.packt.masteringakka.bookstore.inventory.InventoryAllocated}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocatedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.packt.masteringakka.bookstore.inventory.Datamodel.internal_static_com_packt_masteringakka_bookstore_inventory_InventoryAllocated_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.packt.masteringakka.bookstore.inventory.Datamodel.internal_static_com_packt_masteringakka_bookstore_inventory_InventoryAllocated_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated.class, com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated.Builder.class);
      }

      // Construct using com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        orderId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        amount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        bookId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.packt.masteringakka.bookstore.inventory.Datamodel.internal_static_com_packt_masteringakka_bookstore_inventory_InventoryAllocated_descriptor;
      }

      public com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated getDefaultInstanceForType() {
        return com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated.getDefaultInstance();
      }

      public com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated build() {
        com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated buildPartial() {
        com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated result = new com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.orderId_ = orderId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.amount_ = amount_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.bookId_ = bookId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated) {
          return mergeFrom((com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated other) {
        if (other == com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated.getDefaultInstance()) return this;
        if (other.hasOrderId()) {
          bitField0_ |= 0x00000001;
          orderId_ = other.orderId_;
          onChanged();
        }
        if (other.hasAmount()) {
          setAmount(other.getAmount());
        }
        if (other.hasBookId()) {
          bitField0_ |= 0x00000004;
          bookId_ = other.bookId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOrderId()) {
          
          return false;
        }
        if (!hasAmount()) {
          
          return false;
        }
        if (!hasBookId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryAllocated) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string orderId = 1;
      private java.lang.Object orderId_ = "";
      /**
       * <code>required string orderId = 1;</code>
       */
      public boolean hasOrderId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string orderId = 1;</code>
       */
      public java.lang.String getOrderId() {
        java.lang.Object ref = orderId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          orderId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string orderId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOrderIdBytes() {
        java.lang.Object ref = orderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string orderId = 1;</code>
       */
      public Builder setOrderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string orderId = 1;</code>
       */
      public Builder clearOrderId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        orderId_ = getDefaultInstance().getOrderId();
        onChanged();
        return this;
      }
      /**
       * <code>required string orderId = 1;</code>
       */
      public Builder setOrderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        orderId_ = value;
        onChanged();
        return this;
      }

      // required int32 amount = 2;
      private int amount_ ;
      /**
       * <code>required int32 amount = 2;</code>
       */
      public boolean hasAmount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 amount = 2;</code>
       */
      public int getAmount() {
        return amount_;
      }
      /**
       * <code>required int32 amount = 2;</code>
       */
      public Builder setAmount(int value) {
        bitField0_ |= 0x00000002;
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 amount = 2;</code>
       */
      public Builder clearAmount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        amount_ = 0;
        onChanged();
        return this;
      }

      // required string bookId = 3;
      private java.lang.Object bookId_ = "";
      /**
       * <code>required string bookId = 3;</code>
       */
      public boolean hasBookId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string bookId = 3;</code>
       */
      public java.lang.String getBookId() {
        java.lang.Object ref = bookId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          bookId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string bookId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getBookIdBytes() {
        java.lang.Object ref = bookId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bookId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string bookId = 3;</code>
       */
      public Builder setBookId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        bookId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string bookId = 3;</code>
       */
      public Builder clearBookId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        bookId_ = getDefaultInstance().getBookId();
        onChanged();
        return this;
      }
      /**
       * <code>required string bookId = 3;</code>
       */
      public Builder setBookIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        bookId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.packt.masteringakka.bookstore.inventory.InventoryAllocated)
    }

    static {
      defaultInstance = new InventoryAllocated(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.packt.masteringakka.bookstore.inventory.InventoryAllocated)
  }

  public interface InventoryBackorderedOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string orderId = 1;
    /**
     * <code>required string orderId = 1;</code>
     */
    boolean hasOrderId();
    /**
     * <code>required string orderId = 1;</code>
     */
    java.lang.String getOrderId();
    /**
     * <code>required string orderId = 1;</code>
     */
    com.google.protobuf.ByteString
        getOrderIdBytes();

    // required string bookId = 2;
    /**
     * <code>required string bookId = 2;</code>
     */
    boolean hasBookId();
    /**
     * <code>required string bookId = 2;</code>
     */
    java.lang.String getBookId();
    /**
     * <code>required string bookId = 2;</code>
     */
    com.google.protobuf.ByteString
        getBookIdBytes();
  }
  /**
   * Protobuf type {@code com.packt.masteringakka.bookstore.inventory.InventoryBackordered}
   */
  public static final class InventoryBackordered extends
      com.google.protobuf.GeneratedMessage
      implements InventoryBackorderedOrBuilder {
    // Use InventoryBackordered.newBuilder() to construct.
    private InventoryBackordered(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InventoryBackordered(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InventoryBackordered defaultInstance;
    public static InventoryBackordered getDefaultInstance() {
      return defaultInstance;
    }

    public InventoryBackordered getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InventoryBackordered(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              orderId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              bookId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.packt.masteringakka.bookstore.inventory.Datamodel.internal_static_com_packt_masteringakka_bookstore_inventory_InventoryBackordered_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.packt.masteringakka.bookstore.inventory.Datamodel.internal_static_com_packt_masteringakka_bookstore_inventory_InventoryBackordered_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered.class, com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered.Builder.class);
    }

    public static com.google.protobuf.Parser<InventoryBackordered> PARSER =
        new com.google.protobuf.AbstractParser<InventoryBackordered>() {
      public InventoryBackordered parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InventoryBackordered(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<InventoryBackordered> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string orderId = 1;
    public static final int ORDERID_FIELD_NUMBER = 1;
    private java.lang.Object orderId_;
    /**
     * <code>required string orderId = 1;</code>
     */
    public boolean hasOrderId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string orderId = 1;</code>
     */
    public java.lang.String getOrderId() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          orderId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string orderId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOrderIdBytes() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string bookId = 2;
    public static final int BOOKID_FIELD_NUMBER = 2;
    private java.lang.Object bookId_;
    /**
     * <code>required string bookId = 2;</code>
     */
    public boolean hasBookId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string bookId = 2;</code>
     */
    public java.lang.String getBookId() {
      java.lang.Object ref = bookId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bookId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string bookId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBookIdBytes() {
      java.lang.Object ref = bookId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bookId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      orderId_ = "";
      bookId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasOrderId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBookId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getOrderIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getBookIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getOrderIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getBookIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.packt.masteringakka.bookstore.inventory.InventoryBackordered}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackorderedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.packt.masteringakka.bookstore.inventory.Datamodel.internal_static_com_packt_masteringakka_bookstore_inventory_InventoryBackordered_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.packt.masteringakka.bookstore.inventory.Datamodel.internal_static_com_packt_masteringakka_bookstore_inventory_InventoryBackordered_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered.class, com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered.Builder.class);
      }

      // Construct using com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        orderId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        bookId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.packt.masteringakka.bookstore.inventory.Datamodel.internal_static_com_packt_masteringakka_bookstore_inventory_InventoryBackordered_descriptor;
      }

      public com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered getDefaultInstanceForType() {
        return com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered.getDefaultInstance();
      }

      public com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered build() {
        com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered buildPartial() {
        com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered result = new com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.orderId_ = orderId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.bookId_ = bookId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered) {
          return mergeFrom((com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered other) {
        if (other == com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered.getDefaultInstance()) return this;
        if (other.hasOrderId()) {
          bitField0_ |= 0x00000001;
          orderId_ = other.orderId_;
          onChanged();
        }
        if (other.hasBookId()) {
          bitField0_ |= 0x00000002;
          bookId_ = other.bookId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOrderId()) {
          
          return false;
        }
        if (!hasBookId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.packt.masteringakka.bookstore.inventory.Datamodel.InventoryBackordered) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string orderId = 1;
      private java.lang.Object orderId_ = "";
      /**
       * <code>required string orderId = 1;</code>
       */
      public boolean hasOrderId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string orderId = 1;</code>
       */
      public java.lang.String getOrderId() {
        java.lang.Object ref = orderId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          orderId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string orderId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOrderIdBytes() {
        java.lang.Object ref = orderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string orderId = 1;</code>
       */
      public Builder setOrderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string orderId = 1;</code>
       */
      public Builder clearOrderId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        orderId_ = getDefaultInstance().getOrderId();
        onChanged();
        return this;
      }
      /**
       * <code>required string orderId = 1;</code>
       */
      public Builder setOrderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        orderId_ = value;
        onChanged();
        return this;
      }

      // required string bookId = 2;
      private java.lang.Object bookId_ = "";
      /**
       * <code>required string bookId = 2;</code>
       */
      public boolean hasBookId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string bookId = 2;</code>
       */
      public java.lang.String getBookId() {
        java.lang.Object ref = bookId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          bookId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string bookId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBookIdBytes() {
        java.lang.Object ref = bookId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bookId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string bookId = 2;</code>
       */
      public Builder setBookId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        bookId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string bookId = 2;</code>
       */
      public Builder clearBookId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        bookId_ = getDefaultInstance().getBookId();
        onChanged();
        return this;
      }
      /**
       * <code>required string bookId = 2;</code>
       */
      public Builder setBookIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        bookId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.packt.masteringakka.bookstore.inventory.InventoryBackordered)
    }

    static {
      defaultInstance = new InventoryBackordered(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.packt.masteringakka.bookstore.inventory.InventoryBackordered)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packt_masteringakka_bookstore_inventory_InventoryAllocated_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_packt_masteringakka_bookstore_inventory_InventoryAllocated_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_packt_masteringakka_bookstore_inventory_InventoryBackordered_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_packt_masteringakka_bookstore_inventory_InventoryBackordered_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'src/main/proto/inventorydatamodel.prot" +
      "o\022+com.packt.masteringakka.bookstore.inv" +
      "entory\"E\n\022InventoryAllocated\022\017\n\007orderId\030" +
      "\001 \002(\t\022\016\n\006amount\030\002 \002(\005\022\016\n\006bookId\030\003 \002(\t\"7\n" +
      "\024InventoryBackordered\022\017\n\007orderId\030\001 \002(\t\022\016" +
      "\n\006bookId\030\002 \002(\tB\rB\tDatamodelH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_packt_masteringakka_bookstore_inventory_InventoryAllocated_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_packt_masteringakka_bookstore_inventory_InventoryAllocated_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_packt_masteringakka_bookstore_inventory_InventoryAllocated_descriptor,
              new java.lang.String[] { "OrderId", "Amount", "BookId", });
          internal_static_com_packt_masteringakka_bookstore_inventory_InventoryBackordered_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_packt_masteringakka_bookstore_inventory_InventoryBackordered_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_packt_masteringakka_bookstore_inventory_InventoryBackordered_descriptor,
              new java.lang.String[] { "OrderId", "BookId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
